### ISSUE TITLE
Relative mode title format

### ISSUE THREAD

**Issue by imbolc** [metonym/svelte-time#12]
Now the timestamp is used as a title in the relative mode. Would you consider changing it to something easy parsable by non-programmers eyes? A `title_format` prop maybe with the `Date.toLocaleString()` by default?

**Comment by metonym** [comment]
Great idea – do you want to work on this?

**Comment by imbolc** [comment]
I haven't done any Typescript, but I'll try

**Comment by imbolc** [comment]
https://github.com/metonym/svelte-time/pull/16/

**Comment by metonym** [comment]
Released in [v0.7.0](https://github.com/metonym/svelte-time/releases/tag/v0.7.0). Thanks again!

**Comment by imbolc** [comment]
Nice, thank you for the great lib :)
