### ISSUE TITLE
Locale options?

### ISSUE THREAD

**Issue by fadhluu** [metonym/svelte-time#2]
I think it's better to add locale options considering dayjs already have it, so other timezone can use relative time format too.

Thanks!^^

**Comment by metonym** [comment]
Per the [dayjs documentation](https://day.js.org/docs/en/i18n/changing-locale), a custom locale can be imported and set as the default locale. I've updated the docs to reflect this.

<script>
  import "dayjs/esm/locale/de";
  import dayjs from "dayjs/esm";

  dayjs.locale("de"); // German locale
</script>
