### ISSUE TITLE
As great as this plugin is, dayjs is blocking the way

### ISSUE THREAD

**Issue by haysquareA** [metonym/svelte-time#21]
I love this plugin as it is all you need regarding what it does, but dayjs is blocking the way to usability.

**Comment by metonym** [comment]
I published [v0.7.1](https://github.com/metonym/svelte-time/releases/tag/v0.7.1) which switches the `dayjs` imports back to CJS from ESM.

This should unblock usage of this library with SvelteKit. The current downside is that it doesn't work with Snowpack, which I've [recorded as a known issue](https://github.com/metonym/svelte-time/issues/23).
