### ISSUE TITLE
Cannot import Time with updated SvelteKit

### ISSUE THREAD

**Issue by WebShapedBiz** [metonym/svelte-time#27]
Hi.

I'm using `svelte-time` in two projects.
The first project uses the SvelteKit version `1.0.0-next.445` and everything works fine.
However, the later project is using SvelteKit version `1.0.0-next.507` and when I add `import Time from "svelte-time";`, immediately I'm getting `500 Internal Error` with an error message in the console saying `SyntaxError: The requested module '/node_modules/dayjs/plugin/relativeTime.js?v=175ce1d1' does not provide an export named 'default' (at dayjs.js?v=175ce1d1:2:8)`

Node version: 16.14.1
npm version: 8.19.2

Cheers.

**Comment by WebShapedBiz** [comment]
Solved with #24

**Comment by jdgamble555** [comment]
I'm getting an import error where it can't find the package.
