### ISSUE TITLE
How to use this inside <title>

### ISSUE THREAD

**Issue by denny64** [metonym/svelte-time#4]
I'm trying to use this within the title header but getting an error saying only 'text' and {tags} can be used inside the <title>

Any ideas?

**Comment by metonym** [comment]
You could use the `dayjs` import from `"svelte-time/src/dayjs"` to format and display the value in the document title. It wraps the `relativeTime` plugin.

```svelte
<script>
  import { dayjs } from "svelte-time/src/dayjs";

  $: time = dayjs().format("MMM DD, YYYY");
</script>

<svelte:head>
  <title>{time}</time>
</svelte:head>
```

**Comment by denny64** [comment]
Thank you @metonym
