### ISSUE TITLE
SvelteKit build fails on dayjs ES module import not supported

### ISSUE THREAD

**Issue by kbsali** [metonym/svelte-time#9]
Hi,

Thanks for this cool lib/component. It works great in dev mode for a Sveltekit project I am developping, but when running `npm run build` it fails with the following error : 
```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/.../node_modules/dayjs/esm' is not supported resolving ES modules imported from /home/.../.svelte-kit/output/server/chunks/index-5e596d58.js
Did you mean to import dayjs/esm/index.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:304:17)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)

```

Any idea how this could be fixed? :pray:

**Comment by metonym** [comment]
@kbsali Thank you for raising this issue.

What SvelteKit version are you using? What adapter?

The [SvelteKit example](https://github.com/metonym/svelte-time/tree/master/examples/sveltekit) uses the latest SvelteKit version with the Node adapter and is able to build successfully.

**Comment by kbsali** [comment]
```
$ npm list| grep svelte
├── @sveltejs/adapter-vercel@1.0.0-next.31
├── @sveltejs/kit@1.0.0-next.201
...
├── svelte@3.44.2
```
So it's with the Vercel adapter. In the end I only started using your component and so it was not too long to implement my own component based on `Intl.DateTimeFormat` and `Intl.RelativeTimeFormat`, making the build work fine. I'd still be interested in getting svelte-time to work, but apparently `dayjs`' maintainer is not really reactive at updating his lib :/

**Comment by imbolc** [comment]
There's still an [issue with Vite](https://github.com/sveltejs/kit/issues/699#issuecomment-808742017) (essentially a restart of the dev-server required for every change), which [dayjs v2](https://github.com/iamkun/dayjs/issues/1879) should fix, but they're in alpha and haven't ported `relativeTime` plugin yet.

**Comment by metonym** [comment]
@imbolc Thanks for the info. I'm now encountering a different issue in dev for SvelteKit, and a build error when using Snowpack. I didn't encounter this when linking it locally.

I think I'll have to revert #13.

**Comment by metonym** [comment]
It looks like `dayjs` v2 is still a work in progress; although it's written in ESM, it does not have the `relativeTime` plugin.

An alternative would be to fork `dayjs` and make it compatible.

**Comment by imbolc** [comment]
If everything else except of `relativeTime` works with `dayjs-v2` we could create a `next` branch depending on it. With regard to `relativeTime` we could help them to port the plugin or remove `relative` prop and wait until they port the plugin themselves.

**Comment by haysquareA** [comment]
And today, I'm also facing the same issue using VITE

**Comment by alexmccartneymoore** [comment]
I'm also facing the same issue trying with a 'yup' module, using the node adapter.

**Comment by WebShapedBiz** [comment]
Same issue here, Netlify build failure with error `Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/opt/build/repo/node_modules/dayjs/esm' is not supported resolving ES modules imported from /opt/build/repo/.svelte-kit/output/server/entries/pages/obavijesti.svelte.js
9:35:57 AM: Did you mean to import dayjs/esm/index.js?`

**Comment by metonym** [comment]
**Update**: I published [v0.7.1](https://github.com/metonym/svelte-time/releases/tag/v0.7.1) which switches the `dayjs` imports back to CJS from ESM.

This should unblock usage of this library with SvelteKit.

The current downside is that it doesn't work with Snowpack, which I've [recorded as a known issue](https://github.com/metonym/svelte-time/issues/23). However, I feel that it's better to unblock SvelteKit than Snowpack since SvelteKit/vite has ~30x the usage of Snowpack (based on average NPM downloads).

**Comment by WebShapedBiz** [comment]
Thank you very much @metonym for your time and effort.

**Comment by kbsali** [comment]
thanks @metonym !
To be honest I am not using this component anymore, so I'm not sure what to do with this issue! :) Should I close it, from what I can read I looks like it is fixed now, right?

**Comment by Giszmo** [comment]
I just tried out this plugin using the instructions here on this repo:

```
npm i -D svelte-time

<script>
  import Time from "svelte-time";
</script>

<Time />
```

and get an `import not found: default`.

Might this be related to the use of typescript or did I run into the issue here?

**Comment by metonym** [comment]
@Giszmo What set-up are you using?

**Comment by Giszmo** [comment]
node v18.6.0
typescript ^4.7.4

... what part of set-up do you mean? It was for https://github.com/Giszmo/nostroid

**Comment by metonym** [comment]
> what part of set-up do you mean?

By set-up, I'm referring to SvelteKit/Vite/Rollup etc.

It looks like you're using SvelteKit. From a glance, it looks correct. Are you able to run the [SvelteKit example](https://github.com/metonym/svelte-time/tree/master/examples/sveltekit) locally?

**Comment by Giszmo** [comment]
Everything works totally fine until I try to add svelte-time. The import runs into issues.

If you want me to debug something, I'm around but else, I wrote my own <Time /> widget that's good enough for now.
